services:
  frontend:
    build:
      context: ./hospital-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://51.21.160.18:5171
    image: roman913/hospital-frontend:latest
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./hospital-backend/HospitalManagement
      dockerfile: Dockerfile
    image: roman913/hospital-backend:latest
    restart: always
    ports:
      - "5171:5171"
    environment:
      - ConnectionStrings__HospitalDBConnectionString=Server=db,1433;Database=HospitalManagementDB;User ID=sa;Password=YourStrong!Password123;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/1433' && echo 'Port open' || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 60s

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge
